# Generated by Django 5.1.7 on 2025-04-16 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevSign_Vote', '0006_rename_teamname_team_name_user_teamid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DepartmentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='DevSign_Vote.department'),
        ),
    ]
