# Generated by Django 5.1.7 on 2025-04-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevSign_Vote', '0007_user_departmentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='health_cards',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='DevSign_Vote.healthcard'),
        ),
    ]
