# Generated by Django 5.1.7 on 2025-04-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevSign_Vote', '0008_session_health_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='CreatedBy',
        ),
        migrations.AddField(
            model_name='session',
            name='session_name',
            field=models.CharField(default='placeholder', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='EndTime',
            field=models.DateTimeField(default='2025-12-31 23:59:59'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='Status',
            field=models.CharField(default='Open', max_length=50),
        ),
    ]
