# Generated by Django 5.1.7 on 2025-04-29 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevSign_Vote', '0009_remove_session_createdby_session_session_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='DepartmentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='DevSign_Vote.department'),
        ),
        migrations.AddField(
            model_name='session',
            name='TeamID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='DevSign_Vote.team'),
        ),
    ]
